name: Create Request
description: Request creation of a new short url
title: "Create: "
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: A URL forwarded from the short URL.
      placeholder: ex. https://github.com
    validations:
      required: true
  - type: input
    id: alias
    attributes:
      label: alias
      description: |
        A alias used in the short URL. (https://yaeda.github.io/s/`alias`)
        Only alphanumeric characters, \`-\` and \`_\` can be used.
      placeholder: ex. github
    validations:
      required: false
