name: Create Request
description: Request creation of a new short url
title: "[Creation]: "
labels: ["create-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: url
    attributes:
      label: URL
      description: A URL to be converted to short url.
      placeholder: ex. https://github.com
    validations:
      required: true
  - type: input
    id: alias
    attributes:
      label: alias
      description: A short URL would look like https://yaeda.github.io/s/<alias>.
      placeholder: ex. github
    validations:
      required: false
