name: request

on:
  issues:
    types: [opened, edited]

# Grant GITHUB_TOKEN the permissions
permissions:
  issues: write # to comment to the issue
  contents: write # to update json file
  pull-requests: write # to create pull request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten
        uses: yaeda/shortener@main
